#removing duplicate keys in python is actually pretty tough.  The text will be read in as
# a dict and only 1 of the items will remain.
#to get around this I split up the US and country into two dicts manually, and ran this function:
'''
new_world = {}
to_delete = []
for key,value in US.items():
    for k,v in WORLD.items():
        if key in k:
            #print(f"{k}  {v}  {key}  {value} ")
            new_world[k+'X'] = v
            #print(f"deleting {WORLD[k]}")
            to_delete.append(k)
            
        else:
            new_world[k] = v


for k in to_delete:
    #print(f"deleting: {k}    {WORLD[k]}")
    del new_world[k]

print("\nUS")
for k,v in sorted(US.items()):
    print(f"'{k}':'{v}',")
print("\nWORLD")
for k,v in sorted(WORLD.items()):
    print(f"'{k}':'{v}',")
print("\nnew_world")
for k,v in sorted(new_world.items()):
    print(f"'{k}':'{v}',")
'''
#It just places an X at the end of duplicate world cities and prioritizes US as that will be primarily used

STATE_CODES = {
        'AK':'Alaska',
        'AL':'Alabama',
        'AR':'Arkansas',
        'AS':'American Samoa',
        'AZ':'Arizona',
        'CA':'California',
        'CO':'Colorado',
        'CT':'Connecticut',
        'DC':'District of Columbia (DC)',
        'DE':'Delaware',
        'FL':'Florida',
        'GA':'Georgia',
        'GU':'Guam',
        'HI':'Hawaii',
        'IA':'Iowa',
        'ID':'Idaho',
        'IL':'Illinois',
        'IN':'Indiana',
        'KS':'Kansas',
        'KY':'Kentucky',
        'LA':'Louisiana',
        'MA':'Massachusetts',
        'MD':'Maryland',
        'ME':'Maine',
        'MI':'Michigan',
        'MN':'Minnesota',
        'MO':'Missouri',
        'MP':'Northern Mariana Islands',
        'MS':'Mississippi',
        'MT':'Montana',
        'NA':'National',
        'NC':'North Carolina',
        'ND':'North Dakota',
        'NE':'Nebraska',
        'NH':'New Hampshire',
        'NJ':'New Jersey',
        'NM':'New Mexico',
        'NV':'Nevada',
        'NY':'New York',
        'OH':'Ohio',
        'OK':'Oklahoma',
        'OR':'Oregon',
        'PA':'Pennsylvania',
        'PR':'Puerto Rico',
        'RI':'Rhode Island',
        'SC':'South Carolina',
        'SD':'South Dakota',
        'TN':'Tennessee',
        'TX':'Texas',
        'UT':'Utah',
        'VA':'Virginia',
        'VI':'Virgin Islands',
        'VT':'Vermont',
        'WA':'Washington',
        'WI':'Wisconsin',
        'WV':'West Virginia',
        'WY':'Wyoming',

        #Canada
        'AB': 'Alberta',
        'BC': 'British Columbia',
        'MB': 'Manitoba',
        'NB': 'New Brunswick',
        'NL': 'Newfoundland and Labrador',
        'NT': 'Northwest Territories',
        'NS': 'Nova Scotia',
        'NU': 'Nunavut',
        'ON': 'Ontario',
        'PE': 'Prince Edward Island',
        'QC': 'Quebec',
        'SK': 'Saskatchewan',
        'YT': 'Yukon',

        #Country codes
        'AD':'Andorra',
        'AE':'United Arab Emirates',
        'AF':'Afghanistan',
        'AG':'Antigua',
        'AI':'Anguilla',
        'ALX':'Albania',
        'AM':'Armenia',
        'AO':'Angola',
        'AQ':'Antarctica',
        'ARX':'Argentina',
        'ASX':'American Samoa',
        'AT':'Austria',
        'AU':'Australia',
        'AW':'Aruba',
        'AX':'Aland Islands',
        'BA':'Bosnia',
        'BB':'Barbados',
        'BD':'Bangladesh',
        'BE':'Belgium',
        'BF':'Burkina Faso',
        'BG':'Bulgaria',
        'BH':'Bahrain',
        'BI':'Burundi',
        'BJ':'Benin',
        'BL':'Saint Barthélemy',
        'BM':'Bermuda',
        'BN':'Brunei Darussalam',
        'BO':'Bolivia',
        'BQ':'Bonaire',
        'BR':'Brazil',
        'BS':'Bahamas',
        'BT':'Bhutan',
        'BV':'Bouvet',
        'BW':'Botswana',
        'BY':'Belarus',
        'BZ':'Belize',
        'CAX':'Canada',
        'CC':'Cocos',
        'CD':'Congo',
        'CF':'Central African Republic',
        'CG':'Congo',
        'CH':'Switzerland',
        'CI':"Côte d'Ivoire",
        'CK':'Cook Islands',
        'CL':'Chile',
        'CM':'Cameroon',
        'CN':'China',
        'COX':'Colombia',
        'CR':'Costa Rica',
        'CU':'Cuba',
        'CV':'Cape Verde',
        'CW':'Curaçao',
        'CX':'Christmas Island',
        'CY':'Cyprus',
        'CZ':'Czech Republic',
        'DEX':'Germany',
        'DJ':'Djibouti',
        'DK':'Denmark',
        'DM':'Dominica',
        'DO':'Dominican Republic',
        'DZ':'Algeria',
        'EC':'Ecuador',
        'EE':'Estonia',
        'EG':'Egypt',
        'EH':'Western Sahara',
        'ER':'Eritrea',
        'ES':'Spain',
        'ET':'Ethiopia',
        'FI':'Finland',
        'FJ':'Fiji',
        'FK':'Falkland',
        'FM':'Micronesia',
        'FO':'Faroe',
        'FR':'France',
        'GAX':'Gabon',
        'GB':'United Kingdom',
        'GD':'Grenada',
        'GE':'Georgia',
        'GF':'French Guiana',
        'GG':'Guernsey',
        'GH':'Ghana',
        'GI':'Gibraltar',
        'GL':'Greenland',
        'GM':'Gambia',
        'GN':'Guinea',
        'GP':'Guadeloupe',
        'GQ':'Equatorial Guinea',
        'GR':'Greece',
        'GS':'South Georgia',
        'GT':'Guatemala',
        'GUX':'Guam',
        'GW':'Guinea-Bissau',
        'GY':'Guyana',
        'HK':'Hong Kong',
        'HM':'Heard Island',
        'HN':'Honduras',
        'HR':'Croatia',
        'HT':'Haiti',
        'HU':'Hungary',
        'IDX':'Indonesia',
        'IE':'Ireland',
        'ILX':'Israel',
        'IM':'Isle of Man',
        'INX':'India',
        'IO':'British Indian Ocean Territory',
        'IQ':'Iraq',
        'IR':'Iran',
        'IS':'Iceland',
        'IT':'Italy',
        'JE':'Jersey',
        'JM':'Jamaica',
        'JO':'Jordan',
        'JP':'Japan',
        'KE':'Kenya',
        'KG':'Kyrgyzstan',
        'KH':'Cambodia',
        'KI':'Kiribati',
        'KM':'Comoros',
        'KN':'Saint Kitts and Nevis',
        'KR':'Korea',
        'KW':'Kuwait',
        'KYX':'Cayman Islands',
        'KZ':'Kazakhstan',
        'LAX':'Lao',
        'LB':'Lebanon',
        'LC':'Saint Lucia',
        'LI':'Liechtenstein',
        'LK':'Sri Lanka',
        'LR':'Liberia',
        'LS':'Lesotho',
        'LT':'Lithuania',
        'LU':'Luxembourg',
        'LV':'Latvia',
        'LY':'Libya',
        'MAX':'Morocco',
        'MC':'Monaco',
        'MDX':'Moldova',
        'MEX':'Montenegro',
        'MF':'Saint Martin',
        'MG':'Madagascar',
        'MH':'Marshall Islands',
        'MK':'Macedonia',
        'ML':'Mali',
        'MM':'Myanmar',
        'MNX':'Mongolia',
        'MOX':'Macao',
        'MPX':'Northern Mariana Islands',
        'MQ':'Martinique',
        'MR':'Mauritania',
        'MSX':'Montserrat',
        'MTX':'Malta',
        'MU':'Mauritius',
        'MV':'Maldives',
        'MW':'Malawi',
        'MX':'Mexico',
        'MY':'Malaysia',
        'MZ':'Mozambique',
        'NAX':'Namibia',
        'NCX':'New Caledonia',
        'NEX':'Niger',
        'NF':'Norfolk Island',
        'NG':'Nigeria',
        'NI':'Nicaragua',
        'NL':'Netherlands',
        'NO':'Norway',
        'NP':'Nepal',
        'NR':'Nauru',
        'NU':'Niue',
        'NZ':'New Zealand',
        'OM':'Oman',
        'PAX':'Panama',
        'PE':'Peru',
        'PF':'French Polynesia',
        'PG':'Papua New Guinea',
        'PH':'Philippines',
        'PK':'Pakistan',
        'PL':'Poland',
        'PM':'Saint Pierre and Miquelon',
        'PN':'Pitcairn',
        'PRX':'Puerto Rico',
        'PS':'Palestine',
        'PT':'Portugal',
        'PW':'Palau',
        'PY':'Paraguay',
        'QA':'Qatar',
        'RE':'Réunion',
        'RO':'Romania',
        'RS':'Serbia',
        'RU':'Russian Federation',
        'RW':'Rwanda',
        'SA':'Saudi Arabia',
        'SB':'Solomon Islands',
        'SCX':'Seychelles',
        'SDX':'Sudan',
        'SE':'Sweden',
        'SG':'Singapore',
        'SH':'Saint Helena',
        'SI':'Slovenia',
        'SJ':'Svalbard and Jan Mayen',
        'SK':'Slovakia',
        'SL':'Sierra Leone',
        'SM':'San Marino',
        'SN':'Senegal',
        'SO':'Somalia',
        'SR':'Suriname',
        'SS':'South Sudan',
        'ST':'Sao Tome and Principe',
        'SV':'El Salvador',
        'SX':'Sint Maarten',
        'SY':'Syrian Arab Republic',
        'SZ':'Swaziland',
        'TC':'Turks and Caicos Islands',
        'TD':'Chad',
        'TF':'French Southern Territories',
        'TG':'Togo',
        'TH':'Thailand',
        'TJ':'Tajikistan',
        'TK':'Tokelau',
        'TL':'Timor-Leste',
        'TM':'Turkmenistan',
        'TNX':'Tunisia',
        'TO':'Tonga',
        'TR':'Turkey',
        'TT':'Trinidad and Tobago',
        'TV':'Tuvalu',
        'TW':'Taiwan',
        'TZ':'Tanzania',
        'UA':'Ukraine',
        'UG':'Uganda',
        'UM':'United States Minor Outlying Islands',
        'US':'United States',
        'UY':'Uruguay',
        'UZ':'Uzbekistan',
        'VAX':'Holy See',
        'VC':'Saint Vincent and the Grenadines',
        'VE':'Venezuela',
        'VG':'Virgin Islands, British',
        'VIX':'Virgin Islands, U.S.',
        'VN':'Viet Nam',
        'VU':'Vanuatu',
        'WF':'Wallis and Futuna',
        'WS':'Samoa',
        'YE':'Yemen',
        'YT':'Mayotte',
        'ZA':'South Africa',
        'ZM':'Zambia',
        'ZW':'Zimbabwe'
        
}